### ISSUE TITLE
sending certificate chain along with ESNIKeys

### ISSUE THREAD

**Issue by kazuho** [ekr/draft-rescorla-tls-esni#10]
Thank you for working on the draft. I can't be more happy to see someone willing to lead the community towards having a particular ESNI solution.

Considering the fact that omitting the certificate chain and the signature was [one of the options discussed in my draft](https://tools.ietf.org/html/draft-kazuho-protected-sni-00#section-5.3) (was originally suggested by @siyengar), I am happy to support the proposal and am willing to implement it.

OTOH, please let me argue here for sending the certificate-chain along with the ESNIKey.

While I agree that there is no huge difference in terms of security, there are benefits related to performance in sending the certificate chain along with the ESNIKey.

In QUIC, we are discussing how many packets a server can send before the client's address is validated. This is because sending packets to an non-validated address is an vector for amplification attacks. We can resolve the issue by sending the certificate chain along with the ESNIKey and using an encrypted variant of Cached Certificate Extension.

We also revive the possibility of doing 0-RTT using semi-static key, because the key will be signed by the certificate.

I think that providing performance improvement might give people more incentive to start using ESNI.

**Comment by ekr** [comment]
@kazuho: you make a good point here (and thanks for doing your original draft; as you can see,  stole a lot of ideas!) and I think it's something we should look into

I would argue for keeping these two mechanisms separate, for a few reasons:

1. The cached_info indication would be consumed by the hidden server, not the fronting server, so you have the issues I note in Appendix A.

2. If we ultimately want to do 0-RTT priming (which seems interesting) we will likely want different keys with different lifetimes.

3. Not every hidden server may want to support cached_info and so it might make it harder to get wide ESNI deployment.

In line with point 3, I think it may be easier to experiment with the simpler mechanism, because we can easily change the semantics to be the ones you propose if we need to, given that the extension is encrypted.

**Comment by kazuho** [comment]
@ekr Thank you for your comments.

> I would argue for keeping these two mechanisms separate, for a few reasons:
> 
> 1. The cached_info indication would be consumed by the hidden server, not the fronting server, so you have the issues I note in Appendix A.
> 
> 2. If we ultimately want to do 0-RTT priming (which seems interesting) we will likely want different keys with different lifetimes.
> 
> 3. Not every hidden server may want to support cached_info and so it might make it harder to get wide ESNI deployment.
> 
> In line with point 3, I think it may be easier to experiment with the simpler mechanism, because we can easily change the semantics to be the ones you propose if we need to, given that the extension is encrypted.

I would argue that these three concerns could be resolved by sending the certificate as an optional feature (as well as the 0-RTT a flag in the ESNIKey structure).

But having that said, it really depends on if client and resolver developers want to implement. I also understand that a small step is a good thing.

Please feel free to close the issue (or float it around if you think we might revisit).

OTOH, having an `extensions` field might be always a good idea.

**Comment by martinthomson** [comment]
FWIW, you should remember that cached-info will reveal the identity of the server as effectively as SNI.

I think that I agree with ekr here: priming clients with certificates is valuable, as is priming them for 0-RTT, but both require

I think that protecting ALPN is of far less interest.  Also, as ekr observes, the lifetime for these keys might be dramatically different.  All in all, that makes me lean more toward the piecemeal approach that this draft suggests, as opposed to the "just encrypt extensions" approach that Richard considered.

**Comment by kazuho** [comment]
> FWIW, you should remember that cached-info will reveal the identity of the server as effectively as SNI.

What I am arguing for is "an encrypted variant of Cached Certificate Extension", which is sent by client using the ESNIKey.

**Comment by martinthomson** [comment]
I don't think we need extensions.  If we miss something, we can add another extension.  We had extensions in (the unencrypted) SNI, and they ended up being unused and unusable eventually.  And there was a clear intended use for those even.

**Comment by kazuho** [comment]
I think we might be having a confusion here.

What I am arguing for is adding an extensions slot to ESNIKey, which is currently defined as:
```
struct {
    ESNIKeyShareEntry keys<4..2^16-1>;
    CipherSuite cipher_suites<2..2^16-2>;
    uint16 padded_length;
} ESNIKeys;
```

This structure is sent as a DNS record; you cannot extend it. If we want to add additional attributes, we would be forced to define a new DNS record that gets queried simultaneously. I do not think we do not want to do that.

I totally agree that we do not need the capability to extend the EncryptedSNI structure.

**Comment by martinthomson** [comment]
Ahh, I see what you mean.  Yeah, that's probably fine.
