### ISSUE TITLE
wildcard delegations to hidden server

### ISSUE THREAD

**Issue by kazuho** [ekr/draft-rescorla-tls-esni#25]
Current text says:
> If the serialized ServerNameList is longer than ESNIKeys.padded_length, the client MUST NOT use
the "encrypted_server_name" extension.

However, I am not sure if this is the desired behavior. I would rather suggest encrypting even when the hostname exceeds the padded_length. Having some protection is better than none.

The issue is that in certain deployments it is impossible to guess what the maximum length of the hostname will be. Consider `*.github.io`. It uses a wildcard certificate. Anybody can add a new hostname of any length by creating a new Github account (it might be true that Github some limitation on the length, but that does not necessarily mean that Github shares the maximum length information with the fronting CDN, assuming that it uses a CDN).

**Comment by kazuho** [comment]
I have filed #26 that fixes another issue (it's just a clarification of an open issue) related to wildcard delegation.

**Comment by kazuho** [comment]
Yes. So the question is if a CDN that has a wildcard mapping needs to set `padded_length` to 253 (since current text is a MUST NOT for sending a server name longer than the padded_length), or if we should introduce a different rule.

**Comment by DavidSchinazi** [comment]
How about something like:

padded_length : The length to pad the ServerNameList value to prior to encryption. This value SHOULD be set to the largest ServerNameList the fronting server expects to support rounded up the nearest multiple of 16. If the fronting server supports wildcard names, it SHOULD set this value to 256.

**Comment by kazuho** [comment]
@DavidSchinazi Thank you for the suggestion.

I was feeling uneasy (and am still feeling a bit) about requiring the client to send an ESNI extension as large as ~300 bytes, assuming that CDN's would have at least one wildcard mappings.

But it's about the first packet sent from the client, and we typically have enough room even when 0-RTT data is involved. So I think that we can live with that.

**Comment by kazuho** [comment]
To be closed by #48.

**Comment by kazuho** [comment]
Closed by #48.
