### ISSUE TITLE
Why single A and AAAA requirements?

### ISSUE THREAD

**Issue by ghedo** [ekr/draft-rescorla-tls-esni#29]
Regarding:
```
Servers SHOULD configure DNS such that, upon querying a domain name with ESNI support, at most one each of A, AAAA, TXT ESNI, and ALTSVC {{?I-D.schwartz-httpbis-dns-alt-svc}} Resource Record is returned.
```
Why is that a SHOULD? Does it apply to both fronting and shared mode?

For reference, Cloudflare almost always sends at least two A and AAAA answers for every question.

(I get that it's not a MUST, though I'd also like to understand what the reasoning is in the first place)

**Comment by ekr** [comment]
@chris-wood ??

**Comment by chris-wood** [comment]
@ghedo works for me :)
