### ISSUE TITLE
Add text regarding fallback

### ISSUE THREAD

**Issue by chris-wood** [ekr/draft-rescorla-tls-esni#33]

**Comment by chris-wood** [comment]
Any on-path active attacker can send an unsigned alert in response to a CH it doesn't like, so perhaps it's best just to acknowledge this.

**Comment by DavidSchinazi** [comment]
More than acknowledge this, should we make a recommendation as to whether the client should fail hard or fallback to unencrypted SNI?

**Comment by chris-wood** [comment]
@DavidSchinazi I don't think so.

**Comment by DavidSchinazi** [comment]
Can you elaborate?

**Comment by chris-wood** [comment]
AFAIK, the 1.3 draft makes no recommendation for dealing with this particular problem, and so I think we shouldn't do so here, either.

**Comment by DavidSchinazi** [comment]
Acknowledging is fine if you explain the properties so implementers can make an informed decision knowing the consequences

**Comment by ekr** [comment]
We now forbid negotiating 1.2.
