### ISSUE TITLE
altsvc

### ISSUE THREAD

**Issue by mcmanus** [ekr/draft-rescorla-tls-esni#34]
I suggest dropping the references to Ben's individual alt-svc in DNS draft.. it hasn't been adopted and its future is murky.

actual alt-svc (the non dns kind) actually requires the use of the plaintext SNI. As those are both cachable and connections to new IP addresses (less linkable) you could consider updating it with mike bishop's https://tools.ietf.org/html/draft-bishop-httpbis-sni-altsvc-01 (also an individual draft atm)

**Comment by ghedo** [comment]
@chris-wood also suggested that the reference might not be needed in https://github.com/ekr/draft-rescorla-tls-esni/pull/31#discussion_r188117285 so I made #44 to actually remove it.
