### ISSUE TITLE
Remove the fronting / hidden server distinction

### ISSUE THREAD

**Issue by kontaxis** [ekr/draft-rescorla-tls-esni#37]
In 3.1 Topologies, in Shared Mode topology the fronting and hidden servers are one and the same.

Fronting Mode Topology is described as "... might not be the origin for any domains, but as a practical matter, it is probably the origin for a large set of innocuous domains".

Why are some domains innocuous and others aren't?
Is it ok for an attacker (adversary) to discover innocuous domains names?

Innocuous domain names may provide cover when the threat model includes censorship.
Is this what you are trying to solve here?
Isn't that orthogonal to ESNI, i.e., architectures where there is a cover reason why a client is communicating with a server? (because it's a known CDN or sth)

In 5.2 Fronting Server Behavior the text says "Upon determining the true SNI, the fronting server then either serves the connection directly (if in Shared Mode), in which case it executes the steps in the following section, or forwards the TLS connection to the hidden server (if in Fronting Mode)."

... or decrypts the TLS connections and forwards plain text traffic to the hidden server. (Bad idea I know)
The question is why should this document describe what happens after a TLS connection is established between a client and server? Seems to deviate from the problem this document is trying to address. (See below)

Introduction implicitly defines the problem as "an on-path attacker to determine the domain name"
This is always true with ESNI between the client and fronting server.
All domain names are hidden, innocuous, non-innocuous, hosted in the fronting or some other server.

I would propose to drop any mention of hidden servers or deployment architectures, just say "server" and in Security Considerations mention that a server SHOULD be configured in a way that it does not leak the identities of domains it wants to protect. I.e., when the SNI / ESNI extension is missing the server SHOULD not return a certificate for a protected site. For example CDNs should just return a certificate for their own domain.

**Comment by mcmanus** [comment]
see also #28

**Comment by ekr** [comment]
We ended up changing the terminology here.
