### ISSUE TITLE
Consider using a new DNS RR Type instead of TXT

### ISSUE THREAD

**Issue by DavidSchinazi** [ekr/draft-rescorla-tls-esni#40]
The current document uses the TXT record for `_esni.example.org`. This will cause multiple issues.

1) There is no IANA registry for prefixes that start with underscores to be used in DNS, so it is valid for existing servers to already be using _esni as part of the FQDN.
2) The TXT record was designed to hold descriptive text, which means operators can already be using it for other descriptions.
3) As described in issue #35 , using a prefix breaks CNAME.
4) TXT requires base64 encoding which adds overhead on the network and recursive resolvers.

The generally recommended way to "stuff it in the DNS" is to create a new RR type for your data. For example DANE established RR type TLSA (52). There is room in the 16bit IANA registry for another value. The key here is that this prevents systems from misinterpreting the TXT record as something else, and it prevents systems from already using it for something else

https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-4

**Comment by kazuho** [comment]
That was previously discussed in #7.

**Comment by DavidSchinazi** [comment]
Thanks for those links, I had missed #7. This makes sense to me. I makes me somewhat uncomfortable to abuse TXT this way but I understand the operational concerns. Feel free to close this issue.
