### ISSUE TITLE
Do you need the nonce?

### ISSUE THREAD

**Issue by martinthomson** [ekr/draft-rescorla-tls-esni#6]
You are mixing ClientHello.random in.  That would seem to be sufficient.  From that you can generate the AEAD nonce and key as though this were record protection.

```
esni_secret = HKDF-Extract(0, Z)
k = HKDF-Expand-Label(esni_secret, "esni key", ClientHello.random, L)
iv = HKDF-Expand-Label(esni_secret, "esni key", ClientHello.random, L)
```

We don't need another reason for people to complain about exposing the random number generator state to the network.

**Comment by chris-wood** [comment]
If servers choose to use the same ESNI and semi-static key, not generating and including a nonce could lead to nonce-reuse for 0-RTT data. We talked about just prohibiting this sort of key sharing for servers, though it's good to have a client-side defense against it.
