### ISSUE TITLE
Is DNS query for server or origin

### ISSUE THREAD

**Issue by mcmanus** [ekr/draft-rescorla-tls-esni#61]
The TLS server name (and thus SNI) is the HTTP origin name, however it is not necessarily the same as the host name of the TLS server. HTTP Alternative Services is the obvious way that happens - but Alt-Svc never changes the origin name.

When fetching the ESNI key, do we fetch it from _esni.origin-name or _esni.host-name?

I think origin-name makes more sense - keeping everything that is an expiicit protocol element in terms of origin eliminates confusion.

the counter argument is that you can use alt-svc to do fine grained fanout to providers with different keys (using cdn specific names for them in alt-svc) in a way that is harder to do through the origin name dns controls.

**Comment by kazuho** [comment]
PS. To give an example, golang's TLS API to establish a new connection looks like below.
```
conn, err := tls.Dial("tcp", "mail.google.com:443", &tls.Config{
    RootCAs: roots,
})
```

As is obvious from the example, name resolution happens below the TLS stack. I'd assume that we would want to handle ESNI record lookup within the stack as well.

Therefore, the name used to lookup the ESNI record cannot be the origin name, which is specific to the behavior defined in HTTP (alt-svc). It needs to be the hostname that is used for the name resolution (or a name that is derived from that).

My understanding is that TLS stacks on other programming language often has the same abstraction; i.e. handle name resolution below in the TLS connection establishment call (or the TCP connection establishment call).

**Comment by mcmanus** [comment]
> My view is that the base name that is used to lookup the ESNI value (i.e. the name excluding the `_esni.` prefix) must be the same as the hostname that is carried by the ESNI extension.
> 

to be clear - that is the origin name. In the case of alt-svc, where the host name and the origin name diverge, the SNI remains the origin name. This is also the identity that the client stack will authenticate. The host name is resolved to get a a/aaaa but never appears on the wire.

> ESNI is a replacement for SNI, and I think that the design should allow the TLS stack to obtain the ESNI key by itself (i.e. by querying `_esni.<sni-name>`).

This matches my opinion, and also what firefox nightly is currently doing.. but I'm confused by your next comment

> PS. To give an example, golang's TLS API to establish a new connection looks like below.
> 
> ```
> conn, err := tls.Dial("tcp", "mail.google.com:443", &tls.Config{
>     RootCAs: roots,
> })
> ```
> As is obvious from the example, name resolution happens inside the TLS stack. I'd assume that we would want to handle ESNI record lookup within the stack as well.

afaict the SNI information actually comes from tls.Config (Falling back to mail.google.com only if not provided).. this is no doubt also the information used to authenticate the cert.. https://golang.org/src/crypto/tls/tls.go?s=3255:3347#L88

The TLS stack is going to need both pieces of information. So which should it use?
> 
> Therefore, the name used to lookup the ESNI record cannot be the origin name, which is specific to the behavior defined in HTTP (alt-svc), which operates above the TLS stack. 

no - the origin name is the SNI name even with alt-svc. It might not be the host name.

> It needs to be the hostname that is used for the name resolution (or a name that is derived from that).
> 

I think that's defensible but for different reasons (key management flexibility). but I would argue against this as we don't really want you using large sets of keys

> My understanding is that TLS stacks on other programming language often has the same abstraction; i.e. handle name resolution inside in the TLS connection establishment call (or the TCP connection establishment call).

If a stack can't support alt-svc, then this isn't a problem - the name is the same everywhere :)

If a stack does support alt-svc then it has 2 names to deal with.. one is the name used for SNI and auth, and the other is the one used for TCP. (or perhaps it doesn't do TCP on its own).

All this issue is trying to do is decide whether the name we lookup for ENSNI/TXT is the same as the name we lookup for A/AAAA.. I'm going to say that they don't necessarily have to match. (i.e. your A could be for the alt-svc but your txt/esni is always going to be for the origin - which is the same thing you put in your CH.

I'll make a pr.
