### ISSUE TITLE
Contributory behaviour

### ISSUE THREAD

**Issue by martinthomson** [ekr/draft-rescorla-tls-esni#66]
This might not need the same level of rigour as TLS itself, but the construction of the keys could be better.  Right now, Z is dependent on contributory behaviour.

I recommend that rather than just hashing `ClientHello.random`, a pseudo-message be constructed that includes the random, the server advertisement (in its entirety), the client's key share in some form, and maybe the prologue of the esni extension as well.  Essentially the entire mini-protocol we're using.

**Comment by martinthomson** [comment]
Yeah, using Derive-Secret would be best, I think. Try to keep the entire process aligned with existing practice.

**Comment by ekr** [comment]
We didn't do Derive-Secret, but otherwise we did this.
