### ISSUE TITLE
Discuss query strategies and how to deal with loss

### ISSUE THREAD

**Issue by chris-wood** [ekr/draft-rescorla-tls-esni#83]
The order of DNS queries may matter in systems that use Happy Eyeballs. Also, should TLS connections block until ESNI key queries come back? What if they never come back?

**Comment by mcmanus** [comment]
can you elaborate on what you're thinking about wrt he? (assuming the inaddr.arpa plan is off the table)

**Comment by chris-wood** [comment]
Basically addressed in #86.
